apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-root-ca-cert-configmap
  namespace: vik
data:
 self-signed-ca.crt: |
  -----BEGIN CERTIFICATE-----
  MIIDmTCCAoGgAwIBAgIUVd+kJmd044EDZhX0NUJHfm0wzvowDQYJKoZIhvcNAQEL
  BQAwXDELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAkhSMQ8wDQYDVQQHDAZLYXJuYWwx
  DDAKBgNVBAoMA3ZpazEMMAoGA1UECwwDZGV2MRMwEQYDVQQDDAoqcXVvdGUuZGV2
  MB4XDTIzMDEwMTA5NDM0MVoXDTIzMDEzMTA5NDM0MVowXDELMAkGA1UEBhMCSU4x
  CzAJBgNVBAgMAkhSMQ8wDQYDVQQHDAZLYXJuYWwxDDAKBgNVBAoMA3ZpazEMMAoG
  A1UECwwDZGV2MRMwEQYDVQQDDAoqcXVvdGUuZGV2MIIBIjANBgkqhkiG9w0BAQEF
  AAOCAQ8AMIIBCgKCAQEAvyvA4H6FaG0swIctYn5D4QcSKigvdgdYrVkR2sSolsrf
  /dGJDjY8QC3bGACffTKPbkV0GGB8A3iWnpLfmatNbOIfdMGQluZTFn0B3cytJ2q2
  vFPyNzaImTqHim+Khz0sImrbWSkiHx+DRQYlvBPVa8u1QBZ3VD1rt7pYyqPHVXbH
  DIx/quNkoa8VfxpPWqWgoEao5rX8yXJ/vj8c/jDtBYgU74dstOqrV78qAi+sR641
  Wk4dP0wLSrl6qsM37jC2VwXHCfCAnPeLmj316PTBxuqxHSBParQzgABG7WCL2SO6
  ci/DSPGfYpUp6Kc4Na3Gf/S1wc2SSCJ1zgGtV+GgDwIDAQABo1MwUTAdBgNVHQ4E
  FgQUQlBingBQTDbDHnn5PU7xzHnd3XEwHwYDVR0jBBgwFoAUQlBingBQTDbDHnn5
  PU7xzHnd3XEwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAXOxV
  XrwK4eXSgmmv4lXcguNNHtp8ts55IwnNLNY4P/uq475VvDYBv15qzx0igYlIGNp7
  GZ6KXd2Z87k9FOUwZPwlW4FP6pnRvWfVr5z8n59XLTBk7JtHo4zxvab4R+OoLRFx
  C8tcGSV8CoYsvQU4f+B9+yUStPE/IRqnzE+mIFTDHWPfMHR0Kjm2vJbd3atr8UA7
  tiQt/wa3Xu7cF7CJA+OSiGMSzGUj828XHYlFRX6RtwKT2ic46iBFuSRrkReqQrpf
  dU91XshCTO739pQtuW0QasLubXNdMj83LYEjI4ACHVkPZylDCHccyATLlTagAM8g
  zzvWzBMwcVuDs5/9yg==
  -----END CERTIFICATE-----
    